# Azure DevOps pipeline to remove all resources

variables:
- group: terraform-tuesdays

trigger: none
  
jobs:
- job: Destroy_resources  
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraform_version)

    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: $(project_id)
        pipeline: $(pr_pipeline_id)
        artifact: PlanFile

    - task: AzureKeyVault@1
      inputs:
        ConnectedServiceName: $(service_name)
        keyVaultName: $(key_vault_name)
        secretsFilter: '*'
        runAsPreJob: false # Azure DevOps Services only

    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(sas-token)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/2021-07-27-ADO/vnet'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(container-name) -backend-config=key=$(key)'
        backendType: 'selfConfigured'

    - task: TerraformCLI@0
      displayName: Terraform Destroy
      env:
        ARM_SAS_TOKEN: $(sas-token)
        ARM_CLIENT_ID: $(az-client-id)
        ARM_CLIENT_SECRET: $(az-client-secret)
        ARM_SUBSCRIPTION_ID: $(az-subscription)
        ARM_TENANT_ID: $(az-tenant)
      inputs:
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/2021-07-27-ADO/vnet'
